### ISSUE TITLE
Stream a whole week into a deployed cluster

### ISSUE THREAD

**Issue by ericxtang** [livepeer/test-harness#22]
Accomplishing this would give us confidence in the demo deployment as we are out doing demos with potential customers.

@j0sh mentioned a helpful `ffmpeg` command - `ffmpeg -f lavfi -i "testsrc=size=640x480:rate=30" -f lavfi -i "sine=sample_rate=48000" -c:a aac -c:v libx264 -f flv rtmp://localhost/streams/new`

**Comment by darkdarkdragon** [comment]
This [config](https://github.com/livepeer/test-harness/blob/master/examples/demo5.js) was running for 8 days with 6 streams (Bunnies) streamed into it. Failure rates was 4% at max (rarely), average is 0.27%. So this config will handle 5 streams (our) target without problem.

**Comment by j0sh** [comment]
> Failure rates was 4%

Just curious, do we have an idea of what caused the spikes in failures?

**Comment by darkdarkdragon** [comment]
I haven't looked at it in details, but errors was 'Orchestrator busy'. Sessions limit on transcoder was set to 4, so, maybe, four streams is on the verge of capabilities of `n1-highcpu-4` instance.

**Comment by j0sh** [comment]
Any idea of what the average processing time was for the 4% vs 0.27% cases? Might be due to contention for CPU time from other tenants on the physical machine.

**Comment by darkdarkdragon** [comment]
Started it again, will look at stats tomorrow

**Comment by darkdarkdragon** [comment]
I've run it again for couple of days (still running).
In metrics I see record with 4.38% failures, all of them was server busy, with 1781ms average transcode time, but there is records with 1865ms transcode time, but with zero failures, so hard to tell the reason.

**Comment by darkdarkdragon** [comment]
And another thing - recently I've got alert from Stackdriver that my broadcaster is not responding for more than 30 seconds. I've tried to dig up metrics/logs, but wasn't able to understand why it is happened, though this investigation resulted in this [PR](https://github.com/livepeer/lpms/pull/98)
I suspect that possibly it was problem with google's network, but not sure how to diagnose this next time.

**Comment by j0sh** [comment]
Is the raw data available anywhere? Some quick thoughts:

If OrchestratorBusy is the predominant error then we'll likely be seeing a few segments with a really long processing time, but several others that complete abnormally quickly (since they are immediately getting bounced by the transcode queue). I'm also wondering what the variation in transcode time is, especially given a time series; does the 1781ms average include network transit (plus downloading + verifying results)? That only gives us ~11% of wiggle room (out of 2000ms), and if the variation appears high then 11% may not be enough to absorb the expected fluctuations.

I'm happy to do some analysis myself but need the data.

**Comment by darkdarkdragon** [comment]
No, I have deleted instances - not wanted to spend more time on this now, want to postpone this till new metrics will be implemented.

It was [transcodeDur](https://github.com/livepeer/go-livepeer/blob/master/server/segment_rpc.go#L301) time.
If you want I can start up this deployment again, and tomorrow there will be new data.

**Comment by j0sh** [comment]
OK. Just noting that because we've technically achieved the milestones we've been aiming for doesn't mean "we're done"; we still have failures and we still should take the effort to characterize them. It's also not clear to me what our debugging / diagnostic process is here, so it'd be good to take some time to figure that out together.
