### ISSUE TITLE
Benchmark: Throughput for a Simple Livepeer Deployment In A Multi Source Stream Environment

### ISSUE THREAD

**Issue by ericxtang** [livepeer/test-harness#54]
**Setup**
* **Minimal Viable Deployment** - 1 B + 3 O/T + S3 (_if it's easier to use test-harness to deploy here, I think it's ok here.  Even though what we really want to test is offchain mode_)
* Deploy on a few popular machine types in GCP
* Manual scripts to stream video from different sources around the web

**Questions to answer**
* How many streams can we handle and still maintain over 99% success rate?
* When success rate starts to go down, where is the bottleneck?
* What's the average end-to-end latency?

**Comment by angyangie** [comment]
Great idea on how to do this from @j0sh :

There might be simpler ways to micro-benchmark specific setups rather than use test harness; in those cases you're mostly concerned with "how long does it take to process a single segment"

This might help : https://gist.github.com/j0sh/640cadfe39b759c38f953baca11e78b0

So you can probably make a build of that benchmarking program, segment a BBB, gzip things up in a bundle,  and run the program manually on particular instances to see the transcoding throughput (eg, what's the smallest instance that gives us sub-2s processing reliably).

That leads to a cost optimization exercise: is it more effective to run N smaller instances with lower capacity each,  or a single larger instance that may cost more by a factor of N if it has a larger total capacity?

It sounds like part of the goal was to determine the performance profile of each machine type and what our minimums might be? 

On paper, once we understand the performance profile of each machine (coupled with the transcoding configurations we know we need to support) then we should be able to model approximately how many O's we need for a given load / configuration. Then we can test that out in practice. Might be faster than randomly trying dozens of combinations in the test harness.

**Comment by angyangie** [comment]
From @j0sh :

Remaining questions: how many streams? what size instances? Which transcoding configurations?

If we have some fixed requirements then we can measure the throughput. Otherwise we can start from the bottom up, understand the performance profile of a single instance, and determine how well that extrapolates to a networked setup (1B / 3O in this case)

That should also give us some clues if there's anything we need to improve on if the model doesn't match up with reality. For example, I don't expect utilization to be 100% since single-instance benchmarking doesn't account for transit time, so there will be some "loss" or overhead there that needs to be factored into the resource allocation.

Understanding the capacity of a single instance is also important because it's what allows us to set good capacity caps, which helps to distribute load better

So it really depends on the size of the instance we're talking about and the transcoding configurations we want to use. 720p + 360p + 240p ?

**Comment by ericxtang** [comment]
We ran this on AWS (with Apple standard HLS bitrate ladder).  Preliminary results show 10 concurrent streams with 5 x t2.xlarge.

**Comment by j0sh** [comment]
T instances are burstable. Is the performance consistent enough?
